name: Manual Test Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: true
        default: 'Hello World'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.message }}"
