name: Validate Kubernetes Manifests with Kubeconform

on:
  push: # Run on every push to any branch
    branches:
      - main # Or your default branch
      - 'feature/**'
  pull_request: # Also run on pull requests targeting main
    branches:
      - main

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kubeconform
        env:
          KUBECONFORM_VERSION: "0.6.4" # Specify a Kubeconform version (check releases on GitHub)
        run: |
          echo "Downloading Kubeconform version ${KUBECONFORM_VERSION}..."
          wget "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" -O kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform-linux-amd64.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/
          rm kubeconform-linux-amd64.tar.gz
          echo "Kubeconform version $(kubeconform -v) installed."

      - name: Validate Kubernetes YAML files
        # This command assumes your Kubernetes YAML files are in a directory named 'simple-nginx'
        # Adjust the path if your files are located elsewhere.
        run: |
          echo "Validating Kubernetes manifests in the 'simple-nginx' directory..."
          # Ensure the directory exists and contains YAML files to avoid errors
          if [ -d "simple-nginx" ] && [ -n "$(find simple-nginx -maxdepth 1 -name '*.yaml' -print -quit 2>/dev/null)" ]; then
            # -summary: Show a summary of validated files and errors
            # -strict: Disallow unknown properties (recommended for catching typos)
            # -kubernetes-version: Specify your target K8s version for schema validation
            # Kubeconform's default text output is generally concise for valid files when -summary is used.
            kubeconform -summary -strict -kubernetes-version 1.28.0 simple-nginx/**/*.yaml
          else
            echo "No YAML files found in 'simple-nginx' directory or directory does not exist. Skipping validation."
          fi
