name: Validate Kubernetes Manifests

on:
  push: # Run on every push to any branch
    branches:
      - main # Or your default branch
      - 'feature/**'
  pull_request: # Also run on pull requests targeting main
    branches:
      - main

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kubeval
        uses: instrumenta/actions-setup-kubeval@v2 # Sets up kubeval CLI

      - name: Validate Kubernetes YAML files
        # This command assumes your Kubernetes YAML files are in a directory named 'manifests'
        # Adjust the path 'manifests/**/*.yaml' if your files are located elsewhere.
        # You can also validate individual files or multiple directories.
        # --ignore-missing-schemas is used because kubeval might not have schemas for all CRDs by default.
        # For CRDs, you might need to provide their schemas explicitly or use other validation tools like conftest.
        run: |
          echo "Validating Kubernetes manifests in the 'manifests' directory..."
          kubeval --ignore-missing-schemas -d simple-nginx/**/*.yaml
          # Example for a specific file:
          # kubeval my-deployment.yaml

          # If you have multiple directories:
          # kubeval -d k8s-configs-dir1/**/*.yaml -d k8s-configs-dir2/**/*.yaml
